### ISSUE TITLE
How to run on Linux?

### ISSUE THREAD

**Issue by Joshua2504** [suurjaak/InputScope#10]
With a lot of headache because of missing dependencies and very outdated python versions, I got this to install on my Ubuntu Box.

Now the question is how do I run it? There is no command inputscope*

**Comment by suurjaak** [comment]
Those commands should be there, if you installed it with pip. Can you describe how you installed it? 

Another option for running the tray program would be:
- `python -m inputscope`

Or without the tray program, running input listener and the statistics website separately:
- `python -m inputscope.listener`
- `python -m inputscope.webui`

The statistics website will be at http://localhost:8099.

**Comment by Joshua2504** [comment]
pip install inputscope, fixed dependencies

python -m inputscope works
