### ISSUE TITLE
Change Keyboard Layout

### ISSUE THREAD

**Issue by Joshua2504** [suurjaak/InputScope#11]
Hi,

can the keyboard layout changed? It's QWERTY, I do have a QWERTZ Keyboard. 

Running Linux.

Regards

**Comment by suurjaak** [comment]
Not effortlessly, but in principle yes. 

You'd have to update `inputscope/static/keyboard.svg` to your keyboard layout, and update `KeyPositions` in `inputscope/conf.py` accordingly. 

If the only difference is Z vs Y, then that's an easy change, you can just swap out the two letters in either file with a text editor.

**Comment by Joshua2504** [comment]
Where do I find the ``inputscope`` directory?

**Comment by suurjaak** [comment]
That depends on your Python installation specifics. Typically one of `['/home/yourusername/.local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']`. 

You can look it up with pip, e.g. `pip show inputscope` displays the location.
