### ISSUE TITLE
v1.5 not on pypi?

### ISSUE THREAD

**Issue by Gotos** [suurjaak/InputScope#13]
According to https://pypi.org/project/InputScope/, v1.4 seems to be the latest release available in pip. Unfortunately, that version isn't python3 enabled, so installation with pip isn't as trivial as doing `pip install inputscope`.

I could probably work around this, but I suspect that v1.5 not being available is likely a mistake?

**Comment by suurjaak** [comment]
> I suspect that v1.5 not being available is likely a mistake?

Indeed, I had neglected to upload v1.5 to PyPi. 

Available now.

Thank you for informing of this.
