### ISSUE TITLE
I found logs of many duplicate keys.

### ISSUE THREAD

**Issue by tlckfeks** [suurjaak/InputScope#15]
I have been using Inputscope for 3 days.
I checked Inputscope.db and often found logs of many duplicate keys.
I thought about the cause. But I've never pressed keys in such a pattern.
Below is part of the log file. 
https://we.tl/t-cF344m9U6H

I would like to find a solution of this issue.

**Comment by suurjaak** [comment]
Are you sure you do not have multiple instances running? 

If you shut down InputScope and look at the process list, does it have any more entries of InputScope running?

Does the problem persists over reboots?

**Comment by tlckfeks** [comment]
I found the cause of this issue.
When I press and hold a key, InputScope recognizes that I have pressed a key multiple times.
This issue confuses me quite a bit.
In this case, Is there a way for a single log?

And basically, I saw that Inputscope had 4 duplicate processes on task manager.
Is this normal?

**Comment by suurjaak** [comment]
4 duplicate processes is normal, yes (tray app, single instance checker, input listener, web interface).


> In this case, Is there a way for a single log?

Pressing and holding down a key continues to generate keypress events for the operating system, as long as the key is held down. Not sure if there's any good way to tell that apart from somebody typing really really fast.. 

I suppose there could be an configuration flag to discard consecutive keypresses of the same key, if their time interval is less than something like.. 200 milliseconds?

**Comment by tlckfeks** [comment]
https://github.com/virejdasani/KeystrokeCount
https://www.blacksunsoftware.com/mousotron.html

FYI: The above software recognizes the long press as a single keystroke.
I think the duplicated logs generated by long press of a key could affect the reliability of the software.

**Comment by suurjaak** [comment]
On further thinking, seems like a good idea. The upcoming release will discard consecutive keypresses that look to be generated by the key being held down. 

Will keep this issue open until then.

**Comment by suurjaak** [comment]
Released v1.6.

**Comment by tlckfeks** [comment]
This issue has not been fixed yet.
Holding down the keypress still generates a lot of duplicated logs.
