### ISSUE TITLE
An idea for combo

### ISSUE THREAD

**Issue by tlckfeks** [suurjaak/InputScope#21]
I saw that how many times I had used hotkeys in Inputscope's DB.
By the way, I also wanted to know how many kinds of hotkeys I had used.
However, there was no such feature, so I calculated them manually.
It would be nice if InputScope shows how many kinds of hotkeys I have used.

**Comment by suurjaak** [comment]
What do you mean by hotkeys, exactly?

**Comment by tlckfeks** [comment]
http://localhost:8099/keyboard/combos#

Ex)
KEY         COUNT
Hotkey(=Combo) | 49
Hotkey | 41
Hotkey | 38
Hotkey | 34
Hotkey | 33

Average combo interval | 1min 10.14sec
Total time interval | 1d 7h 59min 51.89sec
+++There are **5** Combos

**Comment by suurjaak** [comment]
Sorry, I still don't understand what you are getting at.

**Comment by tlckfeks** [comment]
https://images2.imgbox.com/7e/e3/ykLdlcRZ_o.png

**Comment by suurjaak** [comment]
Ah, you mean to sum up the number of unique combos used.

Sure, I can add that.

**Comment by tlckfeks** [comment]
That's right. :)
Sorry to bother you.

And one more simple question :

How can I check the version of Inputscope that is currently running on my computer?
In many cases, as you know, Software has a Help-About button that contains the software's information.
Alternatively, The version information may be displayed by hovering the mouse pointer over an icon in the tray area.

**Comment by suurjaak** [comment]
I just discovered this omission myself, that currently it does not display version anywhere. Other than writing it in the configuration file. 

I will add it somewhere.

**Comment by suurjaak** [comment]
Released v1.6, it includes counts of unique keys / combos used. 

And the program version is now available in the "Database info" box on statistics pages.
