### ISSUE TITLE
Add an option to ignore input when the cursor is in the center of the screen.

### ISSUE THREAD

**Issue by AIP21** [suurjaak/InputScope#25]
I would like an option to ignore mouse input events when the cursor is in the middle of the screen. When I play a game, the cursor locks to the center of the screen and it messes with the heatmaps. Could you please add an option to ignore those inputs?

**Comment by suurjaak** [comment]
Interesting problem. So there are mouse events recorded during the game, but they're all positioned in screen center?

**Comment by AIP21** [comment]
Yeah, all the heatmap shows is a red dot in the center of the screen. I assume that becuase of how many data points it has at that one position, the rest of the points from normal mouse movement are hidden in the heatmap becuase they are much less concentrated.

**Comment by suurjaak** [comment]
Out of curiosity, can you send a screenshot of your heatmap page?

I suppose I can add a generic option, to specify regions of interest or disinterest for mouse events in the configuration file, e.g.

```python
# Ignore mouse events from center of screen
MouseRegionsOfDisinterest = [[0.49, 0.49, 0.02, 0.02]]
```

**Comment by shenef** [comment]
How about an application block list? When an application on that list is running then capturing of certain inputs could be deactivated.
That could even have additional benefits outside of this issue.

**Comment by suurjaak** [comment]
@shenef An application block list might be even better, indeed. Identified by the executable name or full path.

I will look into it.

**Comment by suurjaak** [comment]
@AIP21 @shenef 

Assuming you've been using Windows, can you check out this pre-release version: https://erki.lap.ee/stuff/inputscope_1.8.dev6_x64.exe?

There are now application-specific stats as well, and applications can be blacklisted or whitelisted in configuration file, as:
```python
# Path can be absolute or relative like "C:\Python\python.exe" or "python.exe",
# and can contain wildcards like "python*".
ProgramBlacklist = {executable path: [] if all inputs else [input or event type, ]}
ProgramWhitelist = {executable path: [] if all inputs else [input or event type, ]}
```
e.g.
```python
# Monitor all inputs from Notepad only
ProgramWhitelist = {"notepad.exe": []}
```
or
```python
# Ignore keypress events from command prompts, and all mouse events from Paint.
ProgramBlacklist = {"cmd.exe": ["keys"], "mspaint.exe": ["mouse"]}
```

**Comment by AIP21** [comment]
This is great, I'll check it out and let you know of any further issues.

Thank you!

**Comment by suurjaak** [comment]
@AIP21 @shenef Comments?

**Comment by AIP21** [comment]
Yes sorry for the late response. It works perfectly for my purposes. I just added the games I wanted ignored and now the new data is much easier to see. Thank you!

This is very specific but would there be a way for me to remove old points that are in the center of the screen? Because my old data is still not visible due to all the old data in the center of the screen.

**Comment by suurjaak** [comment]
Excellent. I will release an official new version presently. 

> This is very specific but would there be a way for me to remove old points that are in the center of the screen?

History can be deleted from the tray menu: right-click on the tray icon, go to "Clear events history", and choose which time period and input to clear.

**Comment by AIP21** [comment]
That's great, thank you. I'm marking this as closed, but feel free to reopen it if needs be.

**Comment by suurjaak** [comment]
v1.8 released.

**Comment by shenef** [comment]
thx, i haven't gotten to actually test the test build but will report back if I encounter any issues with this new release.
