### ISSUE TITLE
add alongside date, a per application filter

### ISSUE THREAD

**Issue by ghost** [suurjaak/InputScope#26]

**Comment by suurjaak** [comment]
Are you making a feature request? Could you describe your idea in more detail?

**Comment by ghost** [comment]
`Are you making a feature request?` yes!
i meant; currently we can only see the 5 most used keys for each application... having an option to see all keys, feels sweet

**Comment by suurjaak** [comment]
I've been thinking of adding some sort of application filter to the detail pages. Will consider it a bit, how to best go about it.

**Comment by ghost** [comment]
since users, if they are logging keys for a long time, may have a long list of applications; maybe sorting it by frequency is a good bet? or having a search bar...

**Comment by suurjaak** [comment]
The newly released v1.9 has an application filter on the heatmap pages. With a search bar, and also option to select individual applications one by one.
