### ISSUE TITLE
Can you update this to track Mouse button 4 and 5?

### ISSUE THREAD

**Issue by KCIV** [suurjaak/InputScope#3]
As the title asks, I tried to go about doing this myself (not just tracking left right middle)

**Comment by suurjaak** [comment]
I'm sorry, I have no idea how I managed to not notice for so long that there are open issues on this project. 

I guess support for mouse buttons 4 and 5 can be added. However, I myself do not have such a mouse. Would you be willing to work in tandem for this?

**Comment by suurjaak** [comment]
In principle, it can support mouse buttons 4-5, as long as the underlying event listener library supports them. 

Closing the issue for now, as I don't have such a mouse myself and OP has not responded.
