### ISSUE TITLE
Got a traceback, then stopped registering key events

### ISSUE THREAD

**Issue by jave** [suurjaak/InputScope#30]
$ inputscope 
/home/joakim/.local/lib/python3.12/site-packages/inputscope/webui.py:233: DeprecationWarning: The default date converter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
  for e in events:
/home/joakim/.local/lib/python3.12/site-packages/inputscope/webui.py:313: DeprecationWarning: The default date converter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
  for e in events:
Unhandled exception in listener callback
Traceback (most recent call last):
  File "/home/joakim/.local/lib/python3.12/site-packages/pynput/_util/__init__.py", line 228, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joakim/.local/lib/python3.12/site-packages/pynput/_util/xorg.py", line 470, in _handler
    self._handle(self._display_stop, event)
  File "/home/joakim/.local/lib/python3.12/site-packages/pynput/keyboard/_xorg.py", line 564, in _handle
    self.on_press(key)
  File "/home/joakim/.local/lib/python3.12/site-packages/pynput/_util/__init__.py", line 144, in inner
    if f(*args) is False:
       ^^^^^^^^
  File "/home/joakim/.local/lib/python3.12/site-packages/inputscope/listener.py", line 475, in <lambda>
    args = dict(on_press=  lambda k, *a, **kw: self.on_event(True,  k),
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joakim/.local/lib/python3.12/site-packages/inputscope/listener.py", line 487, in on_event
    mykey, realkey = self.extract(key)
                     ^^^^^^^^^^^^^^^^^
  File "/home/joakim/.local/lib/python3.12/site-packages/inputscope/listener.py", line 526, in extract
    elif ord("A") <= vk <= ord("Z") or ord("0") <= vk <= ord("9"):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'int' and 'NoneType'

**Comment by jave** [comment]
I can reproduce this when I press a key on the numpad

**Comment by jave** [comment]
the keycodes I get in X doesnt seem to match the keycodes in the source.

xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'

90  KP_0
91  KP_Separator
104 KP_Enter
87  KP_1
88  KP_2
89  KP_3
83  KP_4
84  KP_5
85  KP_6
79  KP_7
80  KP_8
81  KP_9
82  KP_Subtract
86  KP_Add
77  Num_Lock
106 KP_Divide
63  KP_Multiply
133 Super_L
50  Shift_L

in https://github.com/suurjaak/InputScope/blob/master/src/inputscope/listener.py

         96: "Numpad0",
         97: "Numpad1",
         98: "Numpad2",
         99: "Numpad3",
        100: "Numpad4",
        101: "Numpad5",
        102: "Numpad6",
        103: "Numpad7",
        104: "Numpad8",
        105: "Numpad9",

         12: "Numpad-Clear", # Numpad5 without NumLock
        106: "Numpad-Multiply",
        107: "Numpad-Add",
        109: "Numpad-Subtract",
        110: "Numpad-Delete",
        111: "Numpad-Divide",

So I seem to get a traceback for a keycode not mentioned in the src. KP_ENTER is 104 on X aparently, and 104 in src in Numpad8, and I dont get a crash. But KP_0 is 90, and that doesnt have a src mapping, and then it crashes.

Or so it would appear...

**Comment by suurjaak** [comment]
The deprecation warning will be easy to fix, and I will do so in the next release. 

But it looks like there is a bigger problem. Are you using Ubuntu 24? Seems that there have been a number of breaking changes, and the library used for monitoring user inputs is not compatible with the newest things, and the library author is not actively developing it any more. 

I'll have to set up a virtual machine with ubuntu24 and experiment.

**Comment by jave** [comment]
No Im using fedora 39. Thanks for having a look!

**Comment by suurjaak** [comment]
The new v1.11 release should fix these issues.
