### ISSUE TITLE
InputScope logs non-existent and not used key combos

### ISSUE THREAD

**Issue by Quake4Life** [suurjaak/InputScope#31]
![image](https://github.com/suurjaak/InputScope/assets/121139390/a7dc3d7e-9484-4a90-add2-1fd1002fb78c)
There's no way I pressed Ctrl+Backspace or AltGr+Enter or any like those

**Comment by suurjaak** [comment]
What may have happened, is that you e.g. pressed Ctrl and then Backspace, rapidly enough after each other that the operating system did not signal Ctrl being released, before Backspace got signaled as being pressed down. 

Tested this a bit; when I press Backspace very quickly after Ctrl, the event signaling the release of Ctrl does sometimes actually arrive after Backspace. 

Not sure if there is anything to do about this.

**Comment by Quake4Life** [comment]
Is there any way to register after a slightly longer time period?
Combos are my fav statistics actually. But they seem broken to me now :(

пт, 12 апр. 2024 г. в 17:27, Erki Suurjaak ***@***.***>:

**Comment by suurjaak** [comment]
At the moment I can't really see how to differentiate between a legit combo and an inadvertent one. The keyboard events arrive as they do, and a legit combo may get released equally rapidly.

**Comment by suurjaak** [comment]
@Quake4Life Do you think there is anything that can be done with this issue?

**Comment by Quake4Life** [comment]
If there is no way to set "active window" in milliseconds after which combo
is no longer registered, unfortunately, no

ср, 24 апр. 2024 г., 12:06 Erki Suurjaak ***@***.***>:
