### ISSUE TITLE
i ran it multiple times and it made my mouse drifty

### ISSUE THREAD

**Issue by ghost** [suurjaak/InputScope#6]
i literally just ran it and my mouse started moving around the screen

windows 10 2004

**Comment by suurjaak** [comment]
If you meant to say that the mouse started lagging, then that might be because it currently writes every input event to the database immediately. 

The next version will handle database writes in bigger batches.

**Comment by ghost** [comment]
alright! just making sure you knew.

**Comment by suurjaak** [comment]
Reopening the issue, so that I can verify that the problem has been solved once the next version is released.

**Comment by suurjaak** [comment]
Database writes should no longer cause notable lag in the new v1.3 release. 

Can you confirm?

**Comment by ghost** [comment]
it works!

**Comment by wozniak** [comment]
it works

**Comment by fynntheperson** [comment]
fart
